/**
 * Render context — everything the renderer and the field resolver need, supplied
 * by the caller. Deliberately hook-free: the renderer must be usable inside a
 * hidden print portal, inside a designer canvas, and 4-up in a bulk grid, so
 * context (timezone formatter, attributes, company profile) is passed in rather
 * than pulled from React context inside the render tree.
 */

export interface PrintContext {
    workOrder: any;
    parentMO: any;
    /** Pre-generated QR data URL. Generated by the caller so bulk print does it once per WO. */
    qrDataUrl?: string;
    companyName?: string;
    /** Free-text department typed at print time. */
    department?: string;
    /** Already-formatted "today" string. */
    printDate: string;
    /** Timezone-aware date formatter for record dates. */
    formatDate: (iso: string) => string;
    /** Resolve a system attribute value carried by the MO, by system_role. */
    moAttributeValue: (systemRole: string) => string;
}

export interface BuildContextArgs {
    workOrder: any;
    parentMO: any;
    qrDataUrl?: string;
    companyName?: string;
    department?: string;
    attributes?: any[];
    /** TimezoneContext's `formatCustom`. */
    tzFormatCustom: (iso: string, opts: Intl.DateTimeFormatOptions, locale?: string) => string;
}

const SHORT_DATE: Intl.DateTimeFormatOptions = { day: '2-digit', month: '2-digit', year: '2-digit' };

/**
 * Assemble a PrintContext. The attribute lookup mirrors the old weaving card:
 * find the system attribute by `system_role`, then the value the MO carries in
 * `attribute_value_ids`.
 */
export function buildPrintContext({
    workOrder, parentMO, qrDataUrl, companyName, department, attributes = [], tzFormatCustom,
}: BuildContextArgs): PrintContext {
    const moValueIds: string[] = parentMO?.attribute_value_ids || [];

    const moAttributeValue = (systemRole: string): string => {
        const attr = (attributes || []).find(
            (a: any) => (a.system_role || '').toLowerCase() === systemRole.toLowerCase()
        );
        const value = attr?.values?.find((v: any) => moValueIds.includes(v.id));
        return value?.value || '';
    };

    return {
        workOrder,
        parentMO,
        qrDataUrl,
        companyName,
        department,
        printDate: new Date().toLocaleDateString('id-ID', { day: '2-digit', month: '2-digit', year: 'numeric' }),
        formatDate: (iso: string) => tzFormatCustom(iso, SHORT_DATE, 'id-ID'),
        moAttributeValue,
    };
}
