import pytest
import os
from pathlib import Path
from sqlalchemy.engine import make_url

# Tests must never touch the app's own database (`erp`) — force a dedicated
# `erp_test` database on the same server, derived from whatever DATABASE_URL
# the environment already provides (so this works unchanged in Docker and CI).
# Override with TEST_DB_NAME if a run needs a different name (e.g. per xdist worker).
_dev_url = make_url(
    os.environ.get("DATABASE_URL", "postgresql+psycopg2://erp:erp@localhost:5432/erp")
)
_TEST_DB_NAME = os.environ.get("TEST_DB_NAME", "erp_test")
# str(URL) masks the password as a literal "***" in SQLAlchemy 2.x — must render explicitly.
os.environ["DATABASE_URL"] = _dev_url.set(database=_TEST_DB_NAME).render_as_string(hide_password=False)

from fastapi.testclient import TestClient
from sqlalchemy import event as sa_event
from sqlalchemy.orm import Session
from app.main import app
from app.db.session import get_db, engine
from app.core.security import create_access_token
from app.models.auth import User
import uuid

# The `client` fixture enters the app's lifespan, and it does so once PER TEST.
# Startup warms the booking cache, which is the uncapped plant-wide netting pass
# (`/stock/availability`) — minutes of work against a real development database,
# repeated for every test, which reads as a hung suite rather than a slow one.
# Tests never assert on that cache, so it is stubbed out for the whole session.
from app.api import stock as _stock_api
_stock_api.warm_booking_cache = lambda: None

# Every connection a test touches gets a lock timeout, so a lock wait fails the
# test that caused it instead of hanging the run. The fixture connection had one
# already; this covers the app's own pool, which is where a route's write can
# block on a row a test's open transaction is holding. Ten seconds is far longer
# than any statement here legitimately needs.
_TEST_LOCK_TIMEOUT_MS = 10_000


@sa_event.listens_for(engine, "connect")
def _set_test_lock_timeout(dbapi_conn, _record):
    if engine.dialect.name != "postgresql":
        return
    with dbapi_conn.cursor() as cur:
        cur.execute(f"SET lock_timeout = {_TEST_LOCK_TIMEOUT_MS}")
    # Committed, not left open: the statement runs inside psycopg2's implicit
    # transaction, and the pool rolls that back when the connection is returned —
    # which silently reverts the setting and was why a blocked DELETE sat for a
    # minute instead of failing after ten seconds.
    dbapi_conn.commit()


# Use the existing engine but wrap in a transaction that rolls back
@pytest.fixture(scope="function")
def db_session(committed_admin):
    # Depends on the admin purely for ordering: the user must be committed before
    # this transaction opens, and must outlive it (see committed_admin).
    connection = engine.connect()
    transaction = connection.begin()
    session = Session(bind=connection)

    yield session

    session.close()
    transaction.rollback()
    connection.close()

@pytest.fixture(scope="function")
def client(db_session):
    def override_get_db():
        yield db_session
    
    app.dependency_overrides[get_db] = override_get_db
    with TestClient(app, raise_server_exceptions=False) as c:
        yield c
    app.dependency_overrides.clear()

@pytest.fixture(scope="session", autouse=True)
def _test_database():
    """Create a clean `erp_test` database, migrate it, and seed it — once per
    session. Runs before every other fixture (autouse + session scope), and
    `committed_admin` additionally depends on it directly so ordering holds
    even if pytest's autouse-before-explicit rule ever changes.

    Drop-then-create rather than reuse: a stale `erp_test` from an interrupted
    prior run must not leak rows into this one.
    """
    import psycopg2
    from psycopg2 import sql as pg_sql

    maint = _dev_url.set(database="postgres")
    conn = psycopg2.connect(
        host=maint.host, port=maint.port or 5432,
        user=maint.username, password=maint.password,
        dbname="postgres",
    )
    conn.autocommit = True
    try:
        with conn.cursor() as cur:
            cur.execute(
                pg_sql.SQL("DROP DATABASE IF EXISTS {} WITH (FORCE)")
                .format(pg_sql.Identifier(_TEST_DB_NAME))
            )
            cur.execute(
                pg_sql.SQL("CREATE DATABASE {}").format(pg_sql.Identifier(_TEST_DB_NAME))
            )
    finally:
        conn.close()

    # `alembic upgrade head` cannot build schema from scratch: the baseline
    # revision (badce8f1a27f) is a pure ALTER/index diff with zero
    # `create_table` calls — it was autogenerated against an already-existing
    # legacy DB (see scripts/migrate.sh's stamp-vs-upgrade detection, and the
    # project_schema_index_drift memory). Bootstrap the same way that script
    # does for a first deploy: create tables from the current models, then
    # stamp head so later `alembic upgrade` calls in the same run are no-ops.
    from alembic.config import Config
    from alembic import command
    from app.db.base import Base

    Base.metadata.create_all(engine)

    alembic_ini = Path(__file__).resolve().parents[1] / "alembic.ini"
    alembic_cfg = Config(str(alembic_ini))
    alembic_cfg.set_main_option("script_location", str(alembic_ini.parent / "alembic"))
    alembic_cfg.set_main_option("sqlalchemy.url", os.environ["DATABASE_URL"])
    command.stamp(alembic_cfg, "head")

    from app.db.init_db import init_db
    init_db()

    yield


@pytest.fixture(scope="session")
def committed_admin(_test_database):
    """One admin user, committed once for the whole session.

    Session-scoped for two reasons, both learned the hard way:

    * **Teardown order.** Fixtures are finalized in reverse order of setup, so a
      function-scoped user is deleted while `db_session`'s transaction is still
      open — and anything that transaction wrote referencing `users.id` holds a
      lock, so the DELETE waits on it. Session scope moves the delete past every
      test transaction.
    * **Cost.** The row is identical for every test; committing and deleting it
      248 times is pure overhead.

    Committed rather than written into `db_session`: that transaction never
    commits, so async routes on their own connections could not see the user, and
    the previous fixture worked around it by inserting the SAME primary key on a
    second connection — which Postgres turned into a lock wait that hung the run.
    """
    from app.db.session import engine as _eng
    from sqlalchemy.orm import Session as _SASession
    from app.models.auth import Role as _Role

    conn = _eng.connect()
    sess = _SASession(conn)
    # Statements go through the SESSION, never the bare connection: a statement on
    # the connection opens a connection-level transaction, after which this
    # session's commit closes only its own nested one — leaving the insert
    # invisible elsewhere and rolled back at teardown. That is the wrapper trick
    # `db_session` uses deliberately, and it silently defeats a fixture that means
    # to commit.
    admin_role = sess.query(_Role).filter(_Role.name == "Administrator").first()
    user = User(
        # Unique per run: `users.username` is unique, and a leftover row from an
        # earlier run must not collide.
        username=f"testadmin-{uuid.uuid4().hex[:8]}",
        full_name="Test Admin",
        hashed_password="hashed_secret",  # never logged in through the API
        # The seeded Administrator role carries `admin.access`, so every
        # permission-gated route is reachable. Without a role the user
        # authenticates and is then refused with 403.
        role_id=admin_role.id if admin_role else None,
    )
    sess.add(user)
    sess.commit()
    sess.refresh(user)
    user_id = user.id

    yield user

    try:
        sess.query(User).filter(User.id == user_id).delete(synchronize_session=False)
        sess.commit()
    except Exception:
        # Audit rows written by the tests can hold the FK. Leaving one test user
        # behind beats failing teardown.
        sess.rollback()
    finally:
        sess.close()
        conn.close()


@pytest.fixture(scope="function")
def test_user(committed_admin):
    return committed_admin


@pytest.fixture(scope="function")
def auth_headers(test_user):
    token = create_access_token(subject=test_user.id)
    return {"Authorization": f"Bearer {token}"}

_async_timeout_attached = False


def _attach_async_lock_timeout() -> None:
    """Same lock timeout for the async engine, which every async route uses.

    Attached here rather than at import: `db_manager` builds that engine lazily,
    so there is nothing to listen on until the first async route has run.
    """
    global _async_timeout_attached
    if _async_timeout_attached:
        return
    from app.core.db_manager import db_manager
    if db_manager.async_engine is None:
        return
    sync_engine = db_manager.async_engine.sync_engine
    if sync_engine.dialect.name != "postgresql":
        _async_timeout_attached = True
        return

    @sa_event.listens_for(sync_engine, "connect")
    def _set_async_lock_timeout(dbapi_conn, _record):  # pragma: no cover - driver hook
        dbapi_conn.await_(
            dbapi_conn.driver_connection.execute(
                f"SET lock_timeout = {_TEST_LOCK_TIMEOUT_MS}"
            )
        )

    _async_timeout_attached = True


@pytest.fixture(autouse=True)
def dispose_async_engine_pool():
    """
    Dispose the asyncpg connection pool after each test.
    Each TestClient creates a new anyio event loop; asyncpg connections are tied
    to a specific event loop, so connections from test N cannot be reused in test N+1.
    Disposing the pool forces fresh connections bound to the new event loop.
    """
    yield
    _attach_async_lock_timeout()
    from app.core.db_manager import db_manager
    if db_manager.async_engine is not None:
        # dispose() on AsyncEngine is async; access the underlying sync pool directly
        db_manager.async_engine.sync_engine.pool.dispose()
