"""baseline_current_schema

Revision ID: badce8f1a27f
Revises: 
Create Date: 2026-05-10 06:07:55.797348

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'badce8f1a27f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_audit_logs_entity_id'), table_name='audit_logs')
    op.drop_index(op.f('idx_audit_logs_entity_type'), table_name='audit_logs')
    op.drop_index(op.f('idx_audit_logs_timestamp'), table_name='audit_logs')
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_type'), 'audit_logs', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.drop_constraint(op.f('bom_line_values_attribute_value_id_fkey'), 'bom_line_values', type_='foreignkey')
    op.drop_constraint(op.f('bom_line_values_bom_line_id_fkey'), 'bom_line_values', type_='foreignkey')
    op.create_foreign_key(op.f('fk_bom_line_values_attribute_value_id_attribute_values'), 'bom_line_values', 'attribute_values', ['attribute_value_id'], ['id'])
    op.create_foreign_key(op.f('fk_bom_line_values_bom_line_id_bom_lines'), 'bom_line_values', 'bom_lines', ['bom_line_id'], ['id'])
    op.alter_column('bom_lines', 'percentage',
               existing_type=sa.NUMERIC(precision=6, scale=2),
               nullable=False,
               existing_server_default=sa.text('0.0'))
    op.drop_index(op.f('idx_bom_lines_item_id'), table_name='bom_lines')
    op.create_index(op.f('ix_bom_lines_item_id'), 'bom_lines', ['item_id'], unique=False)
    op.drop_constraint(op.f('bom_lines_attribute_value_id_fkey'), 'bom_lines', type_='foreignkey')
    op.drop_constraint(op.f('fk_bom_lines_variant_id_variants'), 'bom_lines', type_='foreignkey')
    op.drop_column('bom_lines', 'attribute_value_id')
    op.drop_constraint(op.f('bom_values_bom_id_fkey'), 'bom_values', type_='foreignkey')
    op.drop_constraint(op.f('bom_values_attribute_value_id_fkey'), 'bom_values', type_='foreignkey')
    op.create_foreign_key(op.f('fk_bom_values_bom_id_boms'), 'bom_values', 'boms', ['bom_id'], ['id'])
    op.create_foreign_key(op.f('fk_bom_values_attribute_value_id_attribute_values'), 'bom_values', 'attribute_values', ['attribute_value_id'], ['id'])
    op.alter_column('boms', 'tolerance_percentage',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=False,
               existing_server_default=sa.text('0.0'))
    op.drop_constraint(op.f('boms_customer_id_fkey'), 'boms', type_='foreignkey')
    op.drop_constraint(op.f('fk_boms_variant_id_variants'), 'boms', type_='foreignkey')
    op.drop_constraint(op.f('boms_attribute_value_id_fkey'), 'boms', type_='foreignkey')
    op.drop_constraint(op.f('boms_work_center_id_fkey'), 'boms', type_='foreignkey')
    op.create_foreign_key(op.f('fk_boms_work_center_id_work_centers'), 'boms', 'work_centers', ['work_center_id'], ['id'])
    op.create_foreign_key(op.f('fk_boms_customer_id_partners'), 'boms', 'partners', ['customer_id'], ['id'])
    op.drop_column('boms', 'attribute_value_id')
    op.drop_constraint(op.f('item_attributes_item_id_fkey'), 'item_attributes', type_='foreignkey')
    op.drop_constraint(op.f('item_attributes_attribute_id_fkey'), 'item_attributes', type_='foreignkey')
    op.create_foreign_key(op.f('fk_item_attributes_attribute_id_attributes'), 'item_attributes', 'attributes', ['attribute_id'], ['id'])
    op.create_foreign_key(op.f('fk_item_attributes_item_id_items'), 'item_attributes', 'items', ['item_id'], ['id'])
    op.drop_index(op.f('idx_items_category'), table_name='items')
    op.drop_index(op.f('idx_items_code_trgm'), table_name='items', postgresql_ops={'code': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_index(op.f('idx_items_name_trgm'), table_name='items', postgresql_ops={'name': 'gin_trgm_ops'}, postgresql_using='gin')
    op.create_index(op.f('ix_items_category'), 'items', ['category'], unique=False)
    op.drop_constraint(op.f('items_attribute_id_fkey'), 'items', type_='foreignkey')
    op.drop_column('items', 'attribute_id')
    op.create_index(op.f('ix_purchase_order_lines_item_id'), 'purchase_order_lines', ['item_id'], unique=False)
    op.create_index(op.f('ix_sales_order_lines_item_id'), 'sales_order_lines', ['item_id'], unique=False)
    op.create_index(op.f('ix_sales_orders_status'), 'sales_orders', ['status'], unique=False)
    op.alter_column('sample_requests', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_sample_requests_base_id'), table_name='sample_requests')
    op.drop_index(op.f('idx_sample_requests_customer_id'), table_name='sample_requests')
    op.drop_index(op.f('idx_sample_requests_so_id'), table_name='sample_requests')
    op.create_index(op.f('ix_sample_requests_base_item_id'), 'sample_requests', ['base_item_id'], unique=False)
    op.create_index(op.f('ix_sample_requests_customer_id'), 'sample_requests', ['customer_id'], unique=False)
    op.create_index(op.f('ix_sample_requests_sales_order_id'), 'sample_requests', ['sales_order_id'], unique=False)
    op.create_index(op.f('ix_sample_requests_status'), 'sample_requests', ['status'], unique=False)
    op.create_index(op.f('ix_stock_balances_batch_key'), 'stock_balances', ['batch_key'], unique=False)
    op.drop_index(op.f('ix_stock_ledger_variant_id'), table_name='stock_ledger')
    op.create_index(op.f('ix_stock_ledger_batch_id'), 'stock_ledger', ['batch_id'], unique=False)
    op.drop_constraint(op.f('fk_stock_ledger_variant_id_variants'), 'stock_ledger', type_='foreignkey')
    op.drop_constraint(op.f('stock_ledger_variant_id_fkey'), 'stock_ledger', type_='foreignkey')
    op.drop_constraint(op.f('stock_ledger_attribute_value_id_fkey'), 'stock_ledger', type_='foreignkey')
    op.drop_column('stock_ledger', 'attribute_value_id')
    op.drop_column('stock_ledger', 'variant_id')
    op.drop_constraint(op.f('stock_ledger_values_stock_ledger_id_fkey'), 'stock_ledger_values', type_='foreignkey')
    op.drop_constraint(op.f('stock_ledger_values_attribute_value_id_fkey'), 'stock_ledger_values', type_='foreignkey')
    op.create_foreign_key(op.f('fk_stock_ledger_values_attribute_value_id_attribute_values'), 'stock_ledger_values', 'attribute_values', ['attribute_value_id'], ['id'])
    op.create_foreign_key(op.f('fk_stock_ledger_values_stock_ledger_id_stock_ledger'), 'stock_ledger_values', 'stock_ledger', ['stock_ledger_id'], ['id'])
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('work_orders', 'qty',
               existing_type=sa.NUMERIC(precision=14, scale=4),
               type_=sa.Float(),
               existing_nullable=True)
    op.create_index(op.f('ix_work_orders_manufacturing_order_id'), 'work_orders', ['manufacturing_order_id'], unique=False)
    op.create_index(op.f('ix_work_orders_status'), 'work_orders', ['status'], unique=False)
    op.drop_constraint(op.f('work_orders_source_location_id_fkey'), 'work_orders', type_='foreignkey')
    op.drop_constraint(op.f('work_orders_sales_order_id_fkey'), 'work_orders', type_='foreignkey')
    op.drop_constraint(op.f('work_orders_parent_wo_id_fkey'), 'work_orders', type_='foreignkey')
    op.drop_constraint(op.f('work_orders_location_id_fkey'), 'work_orders', type_='foreignkey')
    op.drop_constraint(op.f('work_orders_size_id_fkey'), 'work_orders', type_='foreignkey')
    op.drop_column('work_orders', 'parent_wo_id')
    op.drop_column('work_orders', 'location_id')
    op.drop_column('work_orders', 'completed_at')
    op.drop_column('work_orders', 'source_location_id')
    op.drop_column('work_orders', 'size_id')
    op.drop_column('work_orders', 'sales_order_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('work_orders', sa.Column('sales_order_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('work_orders', sa.Column('size_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('work_orders', sa.Column('source_location_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('work_orders', sa.Column('completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('work_orders', sa.Column('location_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('work_orders', sa.Column('parent_wo_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('work_orders_size_id_fkey'), 'work_orders', 'sizes', ['size_id'], ['id'])
    op.create_foreign_key(op.f('work_orders_location_id_fkey'), 'work_orders', 'locations', ['location_id'], ['id'])
    op.create_foreign_key(op.f('work_orders_parent_wo_id_fkey'), 'work_orders', 'work_orders', ['parent_wo_id'], ['id'])
    op.create_foreign_key(op.f('work_orders_sales_order_id_fkey'), 'work_orders', 'sales_orders', ['sales_order_id'], ['id'])
    op.create_foreign_key(op.f('work_orders_source_location_id_fkey'), 'work_orders', 'locations', ['source_location_id'], ['id'])
    op.drop_index(op.f('ix_work_orders_status'), table_name='work_orders')
    op.drop_index(op.f('ix_work_orders_manufacturing_order_id'), table_name='work_orders')
    op.alter_column('work_orders', 'qty',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=14, scale=4),
               existing_nullable=True)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_constraint(op.f('fk_stock_ledger_values_stock_ledger_id_stock_ledger'), 'stock_ledger_values', type_='foreignkey')
    op.drop_constraint(op.f('fk_stock_ledger_values_attribute_value_id_attribute_values'), 'stock_ledger_values', type_='foreignkey')
    op.create_foreign_key(op.f('stock_ledger_values_attribute_value_id_fkey'), 'stock_ledger_values', 'attribute_values', ['attribute_value_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('stock_ledger_values_stock_ledger_id_fkey'), 'stock_ledger_values', 'stock_ledger', ['stock_ledger_id'], ['id'], ondelete='CASCADE')
    op.add_column('stock_ledger', sa.Column('variant_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('stock_ledger', sa.Column('attribute_value_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('stock_ledger_attribute_value_id_fkey'), 'stock_ledger', 'attribute_values', ['attribute_value_id'], ['id'])
    op.create_foreign_key(op.f('stock_ledger_variant_id_fkey'), 'stock_ledger', 'variants', ['variant_id'], ['id'])
    op.create_foreign_key(op.f('fk_stock_ledger_variant_id_variants'), 'stock_ledger', 'variants', ['attribute_value_id'], ['id'])
    op.drop_index(op.f('ix_stock_ledger_batch_id'), table_name='stock_ledger')
    op.create_index(op.f('ix_stock_ledger_variant_id'), 'stock_ledger', ['attribute_value_id'], unique=False)
    op.drop_index(op.f('ix_stock_balances_batch_key'), table_name='stock_balances')
    op.drop_index(op.f('ix_sample_requests_status'), table_name='sample_requests')
    op.drop_index(op.f('ix_sample_requests_sales_order_id'), table_name='sample_requests')
    op.drop_index(op.f('ix_sample_requests_customer_id'), table_name='sample_requests')
    op.drop_index(op.f('ix_sample_requests_base_item_id'), table_name='sample_requests')
    op.create_index(op.f('idx_sample_requests_so_id'), 'sample_requests', ['sales_order_id'], unique=False)
    op.create_index(op.f('idx_sample_requests_customer_id'), 'sample_requests', ['customer_id'], unique=False)
    op.create_index(op.f('idx_sample_requests_base_id'), 'sample_requests', ['base_item_id'], unique=False)
    op.alter_column('sample_requests', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_sales_orders_status'), table_name='sales_orders')
    op.drop_index(op.f('ix_sales_order_lines_item_id'), table_name='sales_order_lines')
    op.drop_index(op.f('ix_purchase_order_lines_item_id'), table_name='purchase_order_lines')
    op.add_column('items', sa.Column('attribute_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('items_attribute_id_fkey'), 'items', 'attributes', ['attribute_id'], ['id'])
    op.drop_index(op.f('ix_items_category'), table_name='items')
    op.create_index(op.f('idx_items_name_trgm'), 'items', ['name'], unique=False, postgresql_ops={'name': 'gin_trgm_ops'}, postgresql_using='gin')
    op.create_index(op.f('idx_items_code_trgm'), 'items', ['code'], unique=False, postgresql_ops={'code': 'gin_trgm_ops'}, postgresql_using='gin')
    op.create_index(op.f('idx_items_category'), 'items', ['category'], unique=False)
    op.drop_constraint(op.f('fk_item_attributes_item_id_items'), 'item_attributes', type_='foreignkey')
    op.drop_constraint(op.f('fk_item_attributes_attribute_id_attributes'), 'item_attributes', type_='foreignkey')
    op.create_foreign_key(op.f('item_attributes_attribute_id_fkey'), 'item_attributes', 'attributes', ['attribute_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('item_attributes_item_id_fkey'), 'item_attributes', 'items', ['item_id'], ['id'], ondelete='CASCADE')
    op.add_column('boms', sa.Column('attribute_value_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(op.f('fk_boms_customer_id_partners'), 'boms', type_='foreignkey')
    op.drop_constraint(op.f('fk_boms_work_center_id_work_centers'), 'boms', type_='foreignkey')
    op.create_foreign_key(op.f('boms_work_center_id_fkey'), 'boms', 'work_centers', ['work_center_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('boms_attribute_value_id_fkey'), 'boms', 'attribute_values', ['attribute_value_id'], ['id'])
    op.create_foreign_key(op.f('fk_boms_variant_id_variants'), 'boms', 'variants', ['attribute_value_id'], ['id'])
    op.create_foreign_key(op.f('boms_customer_id_fkey'), 'boms', 'partners', ['customer_id'], ['id'], ondelete='SET NULL')
    op.alter_column('boms', 'tolerance_percentage',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=True,
               existing_server_default=sa.text('0.0'))
    op.drop_constraint(op.f('fk_bom_values_attribute_value_id_attribute_values'), 'bom_values', type_='foreignkey')
    op.drop_constraint(op.f('fk_bom_values_bom_id_boms'), 'bom_values', type_='foreignkey')
    op.create_foreign_key(op.f('bom_values_attribute_value_id_fkey'), 'bom_values', 'attribute_values', ['attribute_value_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('bom_values_bom_id_fkey'), 'bom_values', 'boms', ['bom_id'], ['id'], ondelete='CASCADE')
    op.add_column('bom_lines', sa.Column('attribute_value_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('fk_bom_lines_variant_id_variants'), 'bom_lines', 'variants', ['attribute_value_id'], ['id'])
    op.create_foreign_key(op.f('bom_lines_attribute_value_id_fkey'), 'bom_lines', 'attribute_values', ['attribute_value_id'], ['id'])
    op.drop_index(op.f('ix_bom_lines_item_id'), table_name='bom_lines')
    op.create_index(op.f('idx_bom_lines_item_id'), 'bom_lines', ['item_id'], unique=False)
    op.alter_column('bom_lines', 'percentage',
               existing_type=sa.NUMERIC(precision=6, scale=2),
               nullable=True,
               existing_server_default=sa.text('0.0'))
    op.drop_constraint(op.f('fk_bom_line_values_bom_line_id_bom_lines'), 'bom_line_values', type_='foreignkey')
    op.drop_constraint(op.f('fk_bom_line_values_attribute_value_id_attribute_values'), 'bom_line_values', type_='foreignkey')
    op.create_foreign_key(op.f('bom_line_values_bom_line_id_fkey'), 'bom_line_values', 'bom_lines', ['bom_line_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('bom_line_values_attribute_value_id_fkey'), 'bom_line_values', 'attribute_values', ['attribute_value_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    op.create_index(op.f('idx_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_index(op.f('idx_audit_logs_entity_type'), 'audit_logs', ['entity_type'], unique=False)
    op.create_index(op.f('idx_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    # ### end Alembic commands ###
