"""Shipment (loading deck) — Surat Jalan moves off PickList

Adds the `shipments` table and `pick_lists.shipment_id`, then backfills one
shipment per already-dispatched pick list so historical delivery notes stay
printable through the single new path.

Hand-written, not autogenerated: this baseline was stamped off a legacy database,
so `--autogenerate` reports a large amount of pre-existing model/DB drift that has
nothing to do with this change (see the schema-index-drift note in CLAUDE.md).
Only the two objects below belong in this revision.

Revision ID: c4e6a8b0d2f7
Revises: b3d5f7a9c1e6
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import UUID


revision: str = 'c4e6a8b0d2f7'
down_revision: Union[str, None] = 'b3d5f7a9c1e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        'shipments',
        sa.Column('id', UUID(as_uuid=True), primary_key=True),
        sa.Column('code', sa.String(length=32), nullable=False),
        sa.Column('delivery_note_number', sa.String(length=64), nullable=True),
        sa.Column('delivery_date', sa.DateTime(), nullable=True),
        sa.Column('customer_name', sa.String(length=255), nullable=True),
        sa.Column('carrier', sa.String(length=128), nullable=True),
        sa.Column('vehicle_plate', sa.String(length=64), nullable=True),
        sa.Column('driver', sa.String(length=128), nullable=True),
        sa.Column('status', sa.String(length=16), nullable=False, server_default='DRAFT'),
        sa.Column('staged_at', sa.DateTime(), nullable=True),
        sa.Column('staged_by_id', UUID(as_uuid=True), sa.ForeignKey('users.id'), nullable=True),
        sa.Column('verified_at', sa.DateTime(), nullable=True),
        sa.Column('verified_by_id', UUID(as_uuid=True), sa.ForeignKey('users.id'), nullable=True),
        sa.Column('verification_notes', sa.Text(), nullable=True),
        sa.Column('verified_with_discrepancy', sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column('dispatched_at', sa.DateTime(), nullable=True),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('created_by_id', UUID(as_uuid=True), sa.ForeignKey('users.id'), nullable=True),
    )
    op.create_index('ix_shipments_code', 'shipments', ['code'], unique=True)
    op.create_index('ix_shipments_status', 'shipments', ['status'])
    op.create_index('ix_shipments_customer_name', 'shipments', ['customer_name'])
    op.create_index('ix_shipments_delivery_note_number', 'shipments', ['delivery_note_number'])

    op.add_column('pick_lists', sa.Column('shipment_id', UUID(as_uuid=True), nullable=True))
    op.create_foreign_key(
        'fk_pick_lists_shipment_id', 'pick_lists', 'shipments',
        ['shipment_id'], ['id'], ondelete='SET NULL',
    )
    op.create_index('ix_pick_lists_shipment_id', 'pick_lists', ['shipment_id'])

    # Backfill: every already-dispatched pick list becomes its own one-member
    # shipment carrying the delivery note it was printed with. Without this, the
    # Surat Jalan for historical orders would be unreachable once the print action
    # moved to the Dispatch page. One-per-pick-list is the honest reconstruction —
    # nothing in the old data recorded which of them shared a truck.
    op.execute("""
        INSERT INTO shipments (
            id, code, delivery_note_number, delivery_date, customer_name,
            carrier, vehicle_plate, driver, status, dispatched_at, notes,
            created_at, created_by_id
        )
        SELECT
            gen_random_uuid(),
            'SHP-L' || lpad((row_number() OVER (ORDER BY pl.created_at, pl.code))::text, 5, '0'),
            COALESCE(pl.delivery_note_number, pl.code),
            COALESCE(pl.delivery_date, pl.dispatched_at),
            so.customer_name,
            pl.carrier, pl.vehicle_plate, pl.driver,
            'DISPATCHED', pl.dispatched_at, pl.notes,
            pl.created_at, pl.created_by_id
        FROM pick_lists pl
        JOIN sales_orders so ON so.id = pl.sales_order_id
        WHERE pl.status = 'DISPATCHED'
    """)
    # Re-link by the note number the shipment was built from. Legacy pick list
    # codes are unique, so COALESCE(delivery_note_number, code) is too.
    op.execute("""
        UPDATE pick_lists pl
        SET shipment_id = s.id
        FROM shipments s
        WHERE pl.status = 'DISPATCHED'
          AND s.status = 'DISPATCHED'
          AND s.code LIKE 'SHP-L%'
          AND s.delivery_note_number = COALESCE(pl.delivery_note_number, pl.code)
    """)


def downgrade() -> None:
    op.drop_index('ix_pick_lists_shipment_id', table_name='pick_lists')
    op.drop_constraint('fk_pick_lists_shipment_id', 'pick_lists', type_='foreignkey')
    op.drop_column('pick_lists', 'shipment_id')
    op.drop_index('ix_shipments_delivery_note_number', table_name='shipments')
    op.drop_index('ix_shipments_customer_name', table_name='shipments')
    op.drop_index('ix_shipments_status', table_name='shipments')
    op.drop_index('ix_shipments_code', table_name='shipments')
    op.drop_table('shipments')
