"""normalize audit_logs entity_type for MOs and WOs

The audit log is queried as `WHERE entity_type = ? AND entity_id = ?` (there is an
index on exactly that pair), so a per-entity history only works if one entity has
one spelling. Two routes wrote a different one: the MO cascade delete logged
`manufacturing_order` instead of `ManufacturingOrder`, and five WO routes logged
`WORK_ORDER` instead of `WorkOrder`. So "everything that happened to this MO"
silently omitted its deletion, and a WO's history omitted its creation, its edits,
its staging and its delete — the only rows that showed up were status changes.

The call sites are fixed in the same change; this rewrites the rows already
written. Down-migration restores the old spellings so the revision is reversible,
even though nothing would want them back.

Hand-written rather than autogenerated: this is a data backfill, not a schema
change, and `--autogenerate` against this schema also picks up unrelated
pre-existing drift.

Revision ID: d5b7f9a1c3e6
Revises: e7b9d1f3a5c2
Create Date: 2026-09-07
"""
from typing import Sequence, Union

from alembic import op

revision: str = 'd5b7f9a1c3e6'
down_revision: Union[str, None] = 'e7b9d1f3a5c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# old spelling -> canonical spelling
RENAMES = (
    ("WORK_ORDER", "WorkOrder"),
    ("manufacturing_order", "ManufacturingOrder"),
)


def upgrade() -> None:
    for old, new in RENAMES:
        op.execute(
            f"UPDATE audit_logs SET entity_type = '{new}' WHERE entity_type = '{old}'"
        )


def downgrade() -> None:
    # Not exact: rows that always carried the canonical spelling are indistinguishable
    # from the backfilled ones, so this moves the whole entity type back. Recorded as a
    # reversal path, not as something to run.
    for old, new in RENAMES:
        op.execute(
            f"UPDATE audit_logs SET entity_type = '{old}' WHERE entity_type = '{new}'"
        )
