"""durable live-event log with a resume cursor

Live events were published to Redis and forgotten. If Redis was unreachable the
publish silently degraded to the emitting worker's own sockets, and a client that
lost its connection had no way to find out what it had missed. This table records
every broadcast before it goes on the bus: `published_at IS NULL` is the retry
queue the relay drains, and `seq` is the cursor a reconnecting client resumes from.

Short retention — the relay prunes it (see EVENT_RETENTION in
services/event_log_service.py). It is a delivery buffer, not an audit trail;
`audit_logs` remains the record of what happened.

Hand-written rather than autogenerated, per the convention in this directory:
`--autogenerate` against this schema also picks up unrelated pre-existing drift.

Revision ID: e39417dc819e
Revises: a2c4e6b8d0f3
Create Date: 2026-08-31
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = "e39417dc819e"
down_revision: Union[str, None] = "a2c4e6b8d0f3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "event_log",
        sa.Column("seq", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("event_type", sa.String(length=64), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("published_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("seq"),
    )
    op.create_index("ix_event_log_event_type", "event_log", ["event_type"])
    op.create_index("ix_event_log_created_at", "event_log", ["created_at"])
    # Partial: the relay only ever scans for rows that never made it onto the bus,
    # which is normally none of them. A full index on published_at would be almost
    # entirely dead weight on the hot INSERT path.
    op.create_index(
        "ix_event_log_unpublished",
        "event_log",
        ["seq"],
        postgresql_where=sa.text("published_at IS NULL"),
    )


def downgrade() -> None:
    op.drop_index("ix_event_log_unpublished", table_name="event_log")
    op.drop_index("ix_event_log_created_at", table_name="event_log")
    op.drop_index("ix_event_log_event_type", table_name="event_log")
    op.drop_table("event_log")
