"""weaving run pause intervals

A loom carries several WOs at once and the floor reprioritises: push one order, park
the others. Each parked stretch is stored as an interval so its working days can be
subtracted from the run's elapsed days — a parked WO holds the efficiency it earned
on the loom instead of decaying for days nobody meant to weave it.

Hand-written rather than autogenerated: `alembic revision --autogenerate` against
this schema also picks up a large amount of unrelated pre-existing drift (print
template indexes, stock_ledger columns, NOT NULL changes), none of which belongs in
this migration.

Revision ID: ffbfa3859715
Revises: a2f4c6e8b0d3
Create Date: 2026-08-21
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = "ffbfa3859715"
down_revision: Union[str, None] = "a2f4c6e8b0d3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "weaving_run_pauses",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("run_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("paused_on", sa.Date(), nullable=False),
        sa.Column("resumed_on", sa.Date(), nullable=True),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("paused_by", sa.String(length=150), nullable=True),
        sa.Column("resumed_by", sa.String(length=150), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["run_id"], ["weaving_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_weaving_run_pauses_run_id"), "weaving_run_pauses", ["run_id"], unique=False
    )
    # At most one OPEN pause per run. The API checks before inserting, but that is
    # check-then-write: two operators hitting Pause on the same card would otherwise
    # both succeed and the run would lose its days twice over.
    op.create_index(
        "uq_weaving_run_pauses_open",
        "weaving_run_pauses",
        ["run_id"],
        unique=True,
        postgresql_where=sa.text("resumed_on IS NULL"),
    )


def downgrade() -> None:
    op.drop_index("uq_weaving_run_pauses_open", table_name="weaving_run_pauses")
    op.drop_index(op.f("ix_weaving_run_pauses_run_id"), table_name="weaving_run_pauses")
    op.drop_table("weaving_run_pauses")
